### ISSUE TITLE
Fonts download links

### ISSUE THREAD

**Issue by WelliSolutions** [mrzool/invoice-boilerplate#25]
To compile the default invoice (on Windows 10), we need fonts:

Hoefler Text: https://fontsgeek.com/fonts/Hoefler-Text-Regular

Helvetica Neue: https://fontsgeek.com/helvetica-neue-font

Perhaps the download links can be added in the Readme.

**Comment by sbwiecko** [comment]
We could also modify the YAML file:
```yaml
# Typography and layout
seriffont: Garamond
sansfont: Arial
```
